### ISSUE TITLE
IOS build Error

### ISSUE THREAD

**Issue by olzii** [endigo/flutter_pdfview#57]
My app is working OK without flutter_pdfview plugin.

With flutter_pdfview, it does not build and run on IOS.  

It gives following error on Android Studio run :  

    /Users/olzii/Desktop/prj/docapp/ios/Runner/GeneratedPluginRegistrant.m:46:9: fatal error: module 'flutter_pdfview' not found
    @import flutter_pdfview;
     ~~~~~~~^~~~~~~~~~~~~~~
Could not build the precompiled application for the device.

on XCode build it gives following error : 

![image](https://user-images.githubusercontent.com/5012289/77830258-4b2a0480-7162-11ea-8bc1-f154e8b5c92a.png)

![image](https://user-images.githubusercontent.com/5012289/77830268-5bda7a80-7162-11ea-9f8e-9aefbf890444.png)

I have tested your EXAMPLE app, it built and run without any problem. What i have done wrong, please help ?

I have searched from Google and made Target Membership to PUBLIC. I it did not help.
![image](https://user-images.githubusercontent.com/5012289/77830383-f470fa80-7162-11ea-8dfa-a6aa054d87b4.png)

Info.plist config :
![image](https://user-images.githubusercontent.com/5012289/77830618-ab21aa80-7164-11ea-9195-2b53de00f651.png)

**Comment by rajababu3** [comment]
@olzii  Even I am facing the same error. Any workaround for this?

**Comment by endigo** [comment]
@rajababu3 Hey, can you share that project because I can't reproduce.

**Comment by rajababu3** [comment]
@endigo Hey, I was able to fix the error by setting ios deployment target to 11. Thank you :)

**Comment by ragaisis** [comment]
With Flutter 1.17.0 I still have problems and can't build even debug project. I've already tried:
- setting target to 11. 
- removing Podfile
- updating / dowgrading flutter_pdfview versions
- updating xCode
- running with xCode and Android studio terminal
- flutter clean

and many more. 

Only reverting to v1.12.13+hotfix.8 fixed the problem.

**Comment by zhenpeng0hou** [comment]
i think i find a way to fix this problem. when i compared `flutter_pdfview.podspec` with `image_picker.podspec`(the podspec file of image_picker plugin) , i found there is  a diffrence between the two podspec files,  there is no `pod_target_xcconfig` property  in `flutter_pdfview.podspec` 。   so i copy the pdfview plugin to my project's pubs directory and  add the line below in the  `flutter_pdfview.podspec`,  then i can build ios with flutter `v1.12.13+hotfix.9`。
`s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS' => 'armv7 arm64 x86_64' }`
[](url)
i am not a ios coder , i just guess the reason of the problem is , without the  `pod_target_xcconfig`  property, the xcode  could not import the pdfview as a module formula. 
@endigo i just fixed this problem in my project . i think  you can release a new version of pdfview  and this may help more people, thank you.

**Comment by endigo** [comment]
@zhenpeng0hou Thanks for your help, I updated the package to 1.0.2.

**Comment by zhenpeng0hou** [comment]
> @zhenpeng0hou Thanks for your help, I updated the package to 1.0.2.

I have updated the package version to 1.0.2 , and  builded iOS successfully.  Thank you.
